- gpu를 이용한 동적 신경망 구축이 가능한 딥러닝 프레임워크
- 텐서의 조작에 GPU를 이용한 병렬처리가 가능함
- C나 CUDA등의 저수준의 고속 병렬처리가 가능하도록 구현
- 중간 레벨은 C++
- 탑레벨은 py api로 래핑한것
- 수많은 모듈들이 py로 작동되도록 구현 되어있음

### 파이토치의 구성 요소
- `torch` : 메인 네임스페이스, 텐서 등의 다양한 함수가 포함
- `torch.autograd` : 자동 미분 기능을 제공하는 라이브러리
- `touch.nn` : 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- `touch.multiprocessing` : 병렬처리 기능을 제공하는 라이브러리
- `torch.optim` : SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- `torch.utils` : 데이터 조작 등 유틸리티 기능 제공
- `torch.onnx` : ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용

### 텐서(Tensors)
- 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
- 다차원 데이터의 표현 방법
- 텐서는 데이터르 담기 위한 컨테이너(container)로써 일반적으로 수치형 데이터를 저장
  - 일종의 상자로 상상할 수 있음
- 넘파이(NumPy)의 ndarray와 유사
- GPU를 사용한 연산 가속 가능

- 0차원 : 스칼라
- 1차원 : 축이 하나
- 2차원 : 축이 두개
- 3차원 : 축이 세개
- 4차원 : 3 * 3 * 3이 여러개
  - 이미지는 3차원 텐서, 여러장의 이미지를 묶으면 4차원 텐서
- 5차원 : 4차원이 여러개
- 6차원 : 5차원이 여러개

In [3]:
import torch
import numpy as np

# pytorch 버전 확인
torch.__version__

'2.5.1'

### 초기화 되지 않은 텐서
- 초기화? : 텐서에 특정 값을 채워서 생성하는 것

In [2]:
x = torch.empty(4,2) # 2d텐서 (row, column)
print(x)

tensor([[-1.8576e+27,  1.6507e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


### 무작위로 초기화된 텐서
- 0과 1사이의 값으로 랜덤하게 초기화된 텐서 생성

In [3]:
x = torch.rand(4,2)
y = torch.randn(2,3)
print(x, y)

tensor([[0.8338, 0.3923],
        [0.9835, 0.0922],
        [0.0935, 0.4413],
        [0.7921, 0.3471]])


### 데이터 타입이 long이고 0으로 채워진 텐서

In [1]:
x = torch.zeros(4,2, dtype=torch.long)
y = torch.ones(2,4, dtype=torch.double)
print(x,y)

NameError: name 'torch' is not defined

### 1로 채워진 텐서, new_ones

### 사용자가 입력한 값으로 텐서 초기화

In [5]:
x = torch.tensor([1, 2.5])
print(x)

tensor([3.0000, 2.3000])

In [5]:
x = torch.ones(2,4, dtype=torch.double)
print(x)

# new_ones는 기존의 텐서의 속성을 물려받음, 데이터 타입과 장치를 물려받음려받음
y = x.new_ones(3,2)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


### 특정 텐서와 같은 타입, 무작위로 값을 채움
- rand_like = 0~1사이 값
- randn_like = 정규분포를 따름

In [6]:
z = torch.randn_like(x, dtype=torch.float)
z

tensor([[ 0.7429, -0.1402, -1.2425, -1.6350],
        [ 0.2701,  0.4138,  1.5765, -0.3131]])

### Numpy에서 불러오기

In [ ]:
data = [1,2,3,4]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


### 텐서의 속성

In [12]:
tensor = torch.rand(3,4)
print(tensor.size()) # 모양
print(tensor.shape) # 모양
print(tensor.dtype) # 자료형
print(tensor.device) # 장치

torch.Size([2, 4])
torch.float32
cpu


### 데이터 타입
- 비트와 가질 수 있는 데이터 범위에 대한 설명

### 특정 데이터 타입의 텐서 생성

In [19]:
ft = torch.FloatTensor([1,2,3])
print(ft.dtype)
tensor = torch.tensor([1,2,3], dtype=torch.float32)
print(tensor.dtype)

torch.float32
torch.float32


### 데이터 타입 캐스팅

In [22]:
ft = torch.FloatTensor([1,2,3])
print(ft.short())
print(ft.int())
print(ft.long()) 

it = torch.IntTensor([1,2,3])
print(it)
print(it.float()) 
print(it.double())
print(it.half())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


### CUDA Tensor

In [30]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

if torch.cuda.is_available():
  tensor = tensor.to("cuda")

# 보통은 아래와 같이 사용
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
print(device)

y = torch.ones_like(x, device=device)

# 디바이스 변경 가능
x = x.to(device)
z = x+y
z.to("cpu", torch.double)
z

tensor([-0.3144])
-0.31437253952026367
torch.float32
cpu


tensor([0.6856])

## 다차원 텐서 표현
- `tensor.ndim` : 차원 정보
- `tensor.shape` : 형상

### 0D Tensor(Scalar)
- 하나의 숫자를 담고 있는 텐서
- 축과 형상이 없음

In [34]:
# 0D Tensor(Scalar)
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


### 1D Tensor(Vector)
- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [33]:
# 1D Tensor(Vector)
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


### 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재
- 일반적인 수치, 통계 데이터셋
- 주로 샘플과 특성을 가진 구조로 사용

In [35]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 3D Tensor
- 큐브(cube)와 같은 모양으로 세개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
- 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재
- 주로 샘플, 타입스텝, 특성을 가진 구조로 사용

In [36]:
t3 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


### 4D Tensor
- 4개의 축
- 컬러 이미지가 대표적인 사례(흑백 이미지 데이터는 3D Tensor로 가능능)
- 주로 샘플, 높이, 너비, 컬러 채널을 가진 구조로 사용

### 5D Tensor
- 5개의 축
- 비디오 데이터가 대표적인 사례
- 주로 샘플, 프레임, 높이, 너비, 컬러 채널을 가진 구조로 사용