## 텐서의 연산

In [1]:
import torch
import math

### 산술 연산

In [ ]:
a = torch.rand(1,2)
a = a * 2
print(a)
a = a - 1
print(a)

In [34]:
x = torch.rand(2,2)
y = torch.rand(2,2)

# in-place(바꿔치기) 연산
y.add_(x)
print(y)

tensor([[0.0731, 0.8669],
        [0.1313, 0.3405]])
tensor([[0.1104, 0.1253],
        [0.4537, 0.0223]])


tensor([[0.1835, 0.9923],
        [0.5850, 0.3629]])

In [35]:
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y)
print(x + y, add) # 더하기

sub = torch.sub(x,y)
print(x - y, sub) # 빼기

mul = torch.mul(x,y)
print(x * y, mul) # 곱하기

div = torch.div(x,y)
print(x / y, div) # 나누기

tensor([[0.7110, 0.3416],
        [0.4325, 0.8710]])
tensor([[0.0622, 0.5248],
        [0.1358, 0.4043]])
tensor([[ 0.6487, -0.1833],
        [ 0.2966,  0.4668]]) tensor([[ 0.6487, -0.1833],
        [ 0.2966,  0.4668]])


In [36]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)
z = torch.mul(x,y)
print(x*y, z)

tensor([[0.0419, 0.1128],
        [0.7160, 0.3204]])
tensor([[0.5309, 0.1133],
        [0.0831, 0.3457]])
tensor([[0.0222, 0.0128],
        [0.0595, 0.1108]]) tensor([[0.0222, 0.0128],
        [0.0595, 0.1108]])


In [37]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)
z = torch.div(x,y)
print(x/y, z)

tensor([[0.9466, 0.2671],
        [0.8045, 0.1105]])
tensor([[0.3965, 0.9638],
        [0.6947, 0.9671]])
tensor([[2.3874, 0.2772],
        [1.1580, 0.1143]]) tensor([[2.3874, 0.2772],
        [1.1580, 0.1143]])


### 각종 연산

In [ ]:
print("절대값", torch.abs(a))
print("올림", torch.ceil(a))
print("반올림", torch.round(a))
print("내림", torch.floor(a))
print("클램프", torch.clamp(a, -0.5, 0.5)) # 조이는 기계

In [38]:
b = torch.randn(2,2)
print("최소값", torch.min(a))
print("최대값", torch.max(a))
print("평균값", torch.mean(a))
print("표준편차", torch.std(a))
print("모든 원소의 합", torch.sum(b))
print("모든 원소의 합", torch.sum(b, dim=0)) # dim 0 첫번째 차원, dim 1 두번째 차원
print("모든 원소의 곱", torch.prod(b))
print("유니크한 값만 선택(중복제거)", torch.unique(torch.tensor([1,2,3,1,2,3,1,1,2,2])))

tensor([[-1.0278, -0.8444],
        [ 0.9349,  0.4557]])
최소값 tensor(-0.4068)
최대값 tensor(0.6218)
평균값 tensor(0.1075)
표준편차 tensor(0.7273)
모든 원소의 합 tensor(-0.4816)
모든 원소의 곱 tensor(0.3698)
유니크한 값만 선택(중복제거) tensor([1, 2, 3])


### argmax, argmin

In [28]:
x = torch.rand(2,2)
# print(x)
# print(x.max(dim=0))
# print(x.max(dim=1))
indicies = x.max(dim=1)
indicies

torch.return_types.max(
values=tensor([0.2836, 0.3834]),
indices=tensor([1, 1]))

### 내적(dot product)

In [40]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)
z = torch.matmul(x,y)
print(z)
w = torch.svd(z)
print(w)

tensor([[0.6591, 0.7992],
        [0.4335, 0.9306]])
tensor([[0.3994, 0.0899],
        [0.1808, 0.4723]])
tensor([[0.4077, 0.4367],
        [0.3413, 0.4784]])
torch.return_types.svd(
U=tensor([[-0.7129, -0.7012],
        [-0.7012,  0.7129]]),
S=tensor([0.8362, 0.0550]),
V=tensor([[-0.6338, -0.7735],
        [-0.7735,  0.6338]]))
