## 텐서의 조작(Manipulations)

In [1]:
import torch

### 인덱싱(Indexing) 
- numpy처럼 인덱싱 가능

In [12]:
x = torch.tensor([[1,2],[3,4]])
print(x)
print(x[0, 0]) # 0행 0열

print(x[0]) # 0행의 값 불러옴

print(x[:, 0]) # 0열의 값 불러옴
print(x[:, 1]) # 1열의 값 불러옴

t = torch.tensor([[1, 2], [3, 4]])
print(t[0, 1])  # 출력: 2


tensor([[1, 2],
        [3, 4]])
tensor(1)
tensor([1, 2])
tensor([1, 3])
tensor([2, 4])


In [ ]:
# 2D 텐서
t = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# (1) 첫 번째 행의 모든 열
print(t[0, :])  # 출력: [1, 2, 3]

# (2) 모든 행의 두 번째 열
print(t[:, 1])  # 출력: [2, 5, 8]

# (3) 첫 번째 행과 두 번째 열의 값
print(t[0, 1])  # 출력: 2

# (4) 첫 번째와 두 번째 행의 두 번째와 세 번째 열
print(t[0:2, 1:3])  # 출력: [[2, 3], [5, 6]]

### 텐서의 크기나 모양을 변경
- `torch.view()`

In [17]:
x = torch.randn(4,5)
print(x)

y = x.view(20)
print(y)

z = y.view(5, -1) # -1은 자동으로
print(z)

tensor([[ 2.2988,  0.3119,  0.8505,  1.1979,  0.5643],
        [ 1.1009,  0.6904,  0.1232,  0.6124,  1.0480],
        [-0.3335,  1.9397, -0.3380, -0.8672, -0.2809],
        [ 1.8433, -0.9317,  0.3486,  0.0256, -0.4010]])
tensor([ 2.2988,  0.3119,  0.8505,  1.1979,  0.5643,  1.1009,  0.6904,  0.1232,
         0.6124,  1.0480, -0.3335,  1.9397, -0.3380, -0.8672, -0.2809,  1.8433,
        -0.9317,  0.3486,  0.0256, -0.4010])
tensor([[ 2.2988,  0.3119,  0.8505,  1.1979],
        [ 0.5643,  1.1009,  0.6904,  0.1232],
        [ 0.6124,  1.0480, -0.3335,  1.9397],
        [-0.3380, -0.8672, -0.2809,  1.8433],
        [-0.9317,  0.3486,  0.0256, -0.4010]])


### 텐서의 숫자값 얻기
- `torch.item()` : 스칼라 값 하나만 존재해야 사용 가능

In [19]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.5054])
0.5053906440734863


### 차원 축소(제거)
- `torch.squeeze()` : 크기가 1인 차원을 줄여줌

In [30]:
x = torch.rand(1, 3, 3)
print(x)
print(x.shape)

y = torch.squeeze(x)
print(y)
print(y.shape)

tensor([[[0.1872, 0.3698, 0.0337]],

        [[0.1201, 0.1792, 0.2698]],

        [[0.1114, 0.9417, 0.2574]]])
torch.Size([3, 1, 3])
tensor([[0.1872, 0.3698, 0.0337],
        [0.1201, 0.1792, 0.2698],
        [0.1114, 0.9417, 0.2574]])
torch.Size([3, 3])


### 차원 증가(생성)
- `torch.unsqueeze()` : dim설정에 따라 변경됨

In [34]:
tensor = torch.rand(3, 3, 3)
print(tensor)
print(tensor.shape)

ts = torch.unsqueeze(tensor, 3) # 0 가장 상위차원 -> 3 가장 하위차원
print(ts)
print(ts.shape)

tensor([[[0.9856, 0.7171, 0.9319],
         [0.4020, 0.3972, 0.2437],
         [0.8736, 0.5690, 0.5863]],

        [[0.8512, 0.6273, 0.3506],
         [0.3335, 0.2429, 0.6819],
         [0.1283, 0.0253, 0.6008]],

        [[0.7903, 0.5933, 0.1898],
         [0.3709, 0.2408, 0.4679],
         [0.5221, 0.2332, 0.7500]]])
torch.Size([3, 3, 3])
tensor([[[[0.9856],
          [0.7171],
          [0.9319]],

         [[0.4020],
          [0.3972],
          [0.2437]],

         [[0.8736],
          [0.5690],
          [0.5863]]],


        [[[0.8512],
          [0.6273],
          [0.3506]],

         [[0.3335],
          [0.2429],
          [0.6819]],

         [[0.1283],
          [0.0253],
          [0.6008]]],


        [[[0.7903],
          [0.5933],
          [0.1898]],

         [[0.3709],
          [0.2408],
          [0.4679]],

         [[0.5221],
          [0.2332],
          [0.7500]]]])
torch.Size([3, 3, 3, 1])


### 텐서간 결합
- `torch.stack()`
  - 동일한 형식의 텐서를 새롭게 '그룹화'함 : 새로운 차원이 생성됨

In [52]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

# new = [x,y,z]
# print(new)
print(torch.stack([x,y,z]))
# d = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
# print(d)

a = torch.tensor([[1, 2], [3, 4]])  # (2, 2)
b = torch.tensor([[5, 6], [7, 8]])  # (2, 2)
c = torch.stack([a,b])
print(c)
print(c.ndim)
print(c.shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])


- `torch.cat()`
  - 데이터를 하나의 텐서로 병합 : 새로운 차원 생성되지X
  - Numpy의 stack과 유사하지만, 쌓을 dim이 존재해야 함
  - 결합하려는 축 외에는 동일해야 함

In [53]:
a = torch.tensor([[1, 2], [3, 4], [5,6]])  # (2, 2)
b = torch.tensor([[5, 6], [7, 8]])  # (2, 2)
c = torch.cat((a,b), dim=0) # dim은 tensor를 결합할 축 0번축: 행, 1번축: 열
print(c)
print(c.shape)
print(c.ndim)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [5, 6],
        [7, 8]])
torch.Size([5, 2])
2


### 텐서 나누기

- `torch.chunk()` : 텐서를 여러개로 나눔
  - 몇개로 나눌지를 지정
  - 나누어 떨어지지 않는 경우, 마지막 조각이 다른 크기를 가질 수 있습니다.

In [58]:
tensor = torch.rand(3,6)
print(tensor)

# (텐서, 나눌 수, 차원(축))
t1, t2, t3 = torch.chunk(tensor, 3, dim=1) # dim은 차원
print(t1, t2, t3)

tensor([[0.6153, 0.0925, 0.4123, 0.2625, 0.1522, 0.8222],
        [0.7711, 0.2194, 0.6604, 0.1322, 0.5243, 0.1511],
        [0.6870, 0.3219, 0.4820, 0.5487, 0.1508, 0.5209]])


(tensor([[0.6153, 0.0925],
         [0.7711, 0.2194],
         [0.6870, 0.3219]]),
 tensor([[0.4123, 0.2625],
         [0.6604, 0.1322],
         [0.4820, 0.5487]]),
 tensor([[0.1522, 0.8222],
         [0.5243, 0.1511],
         [0.1508, 0.5209]]))

- `torch.split()` : 기능은 chunk와 비슷하지만, 나누는 방식이 다름
  - 텐서의 크기가 몇이냐

In [62]:
tensor = torch.rand(3,6)
print(tensor)

# (텐서, 나눌 수, 차원(축))
t1, t2 = torch.split(tensor, 3, dim=1) # dim은 차원
# dim=1이고 size=3이라면 열이 3개가 되도록 나누는 것
t1, t2

tensor = torch.rand(3,6)
print(tensor)

x = torch.tensor([1, 2, 3, 4, 5, 6])

# 크기 2로 나누기
result_x = torch.split(x, split_size_or_sections=2, dim=0)
print(result_x)

y = torch.tensor([1, 2, 3, 4, 5])

# 각각의 크기를 지정
result_y = torch.split(x, split_size_or_sections=[2, 2, 1], dim=0)
print(result_y)


tensor([[0.6766, 0.0658, 0.8299, 0.0079, 0.4463, 0.4774],
        [0.6273, 0.1408, 0.5442, 0.7057, 0.0689, 0.5901],
        [0.5630, 0.2270, 0.4752, 0.3775, 0.9892, 0.3596]])


(tensor([[0.6766, 0.0658, 0.8299],
         [0.6273, 0.1408, 0.5442],
         [0.5630, 0.2270, 0.4752]]),
 tensor([[0.0079, 0.4463, 0.4774],
         [0.7057, 0.0689, 0.5901],
         [0.3775, 0.9892, 0.3596]]))